api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        jsonapi:
            mime_types:
                - application/vnd.api+json

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
