doctrine:
    dbal:
        default_connection: lokr
        connections:
            lokr:
                url: '%env(resolve:DATABASE_URL)%'
                server_version: '5.5'

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: lokr
        entity_managers:
            lokr:
                connection: lokr
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Lokr:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Lokr'
                        prefix: 'App\Entity\Lokr'
                        alias: Lokr